### ISSUE TITLE
Trouble Running the Docker

### ISSUE THREAD

**Issue by JustDr00py** [gristlabs/grist-omnibus#28]
I keep getting this error when trying to run the docker command.

```
Domain is not permitted: Domain must include lower-case letters, numbers, and dashes only.
    at HomeDBManager.unwrapQueryResult (/grist/_build/app/gen-server/lib/homedb/HomeDBManager.js:2312:15)
    at setupDb (/grist/_build/stubs/app/server/server.js:97:16)
    at async main (/grist/_build/stubs/app/server/server.js:133:9) {
  status: 400,
  details: undefined

```
my domain is a normal subdomain of my actual site.

**Comment by JustDr00py** [comment]
Oh you can not use a capital in the TEAM = xxxx
